import os
import io
import matplotlib
matplotlib.use('Agg')  # Non-interactive backend for server environments
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
from typing import Dict, Any, List
from datetime import datetime

from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image, KeepTogether
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.pdfgen import canvas

# Custom Numbered Canvas to display "Page X of Y"
class NumberedCanvas(canvas.Canvas):
    def __init__(self, *args, **kwargs):
        super(NumberedCanvas, self).__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_number(num_pages)
            canvas.Canvas.showPage(self)
        canvas.Canvas.save(self)

    def draw_page_number(self, page_count):
        self.saveState()
        self.setFont("Helvetica", 9)
        self.setFillColor(colors.HexColor("#64748b"))
        
        # Header (Skip on Page 1)
        if self._pageNumber > 1:
            self.drawString(54, 750, "DataInsight AI - Complete Analytics Report")
            self.setStrokeColor(colors.HexColor("#e2e8f0"))
            self.setLineWidth(0.5)
            self.line(54, 742, letter[0] - 54, 742)
            
        # Footer
        page_text = f"Page {self._pageNumber} of {page_count}"
        self.drawRightString(letter[0] - 54, 36, page_text)
        self.drawString(54, 36, "Confidential - Automatically Generated by DataInsight AI")
        self.setStrokeColor(colors.HexColor("#e2e8f0"))
        self.setLineWidth(0.5)
        self.line(54, 48, letter[0] - 54, 48)
        
        self.restoreState()


class PDFService:
    @staticmethod
    def generate_charts_as_buffers(df: pd.DataFrame, df_summary: Dict[str, Any]) -> Dict[str, io.BytesIO]:
        """Generates static matplotlib charts as BytesIO buffers to include in the PDF."""
        buffers = {}
        sns.set_theme(style="white")
        
        # 1. Quality Score Gauge / Summary Bar Chart
        try:
            fig, ax = plt.subplots(figsize=(6, 2.5))
            nulls = df_summary.get("null_summary", {})
            active_nulls = {k: v for k, v in nulls.items() if v > 0}
            if active_nulls:
                cols = list(active_nulls.keys())[:5]
                vals = [active_nulls[c] for c in cols]
                bars = ax.barh(cols, vals, color="#f43f5e", height=0.6)
                ax.bar_label(bars, fmt="%d", padding=3, color="#0f172a", fontsize=9)
                ax.set_title("Missing Values Count by Column (Top 5)", fontsize=11, fontweight="bold", color="#0f172a")
                ax.spines['top'].set_visible(False)
                ax.spines['right'].set_visible(False)
                ax.spines['bottom'].set_visible(False)
                ax.xaxis.set_visible(False)
                plt.tight_layout()
                buf = io.BytesIO()
                plt.savefig(buf, format="png", dpi=150)
                buf.seek(0)
                buffers["null_chart"] = buf
                plt.close(fig)
            else:
                plt.close(fig)
        except Exception:
            plt.close()

        # 2. Correlation Matrix Heatmap
        try:
            num_cols = df.select_dtypes(include=["number"]).columns
            if len(num_cols) > 1:
                fig, ax = plt.subplots(figsize=(5, 4.5))
                corr_df = df[num_cols].corr()
                
                # Draw heatmap
                sns.heatmap(
                    corr_df, 
                    annot=True, 
                    fmt=".2f", 
                    cmap="coolwarm", 
                    vmin=-1, 
                    vmax=1, 
                    center=0, 
                    square=True, 
                    linewidths=.5,
                    cbar_kws={"shrink": .8},
                    ax=ax,
                    annot_kws={"size": 8}
                )
                ax.set_title("Correlation Matrix Heatmap", fontsize=11, fontweight="bold", color="#0f172a")
                plt.xticks(rotation=45, ha='right', fontsize=8)
                plt.yticks(fontsize=8)
                plt.tight_layout()
                buf = io.BytesIO()
                plt.savefig(buf, format="png", dpi=150)
                buf.seek(0)
                buffers["correlation_heatmap"] = buf
                plt.close(fig)
        except Exception:
            plt.close()

        # 3. Categorical distribution (First categorical column top categories)
        try:
            cat_cols = df.select_dtypes(exclude=["number", "datetime"]).columns
            if len(cat_cols) > 0:
                col = cat_cols[0]
                counts = df[col].dropna().value_counts().head(5)
                if len(counts) > 0:
                    fig, ax = plt.subplots(figsize=(6, 3))
                    bars = ax.bar(counts.index.astype(str), counts.values, color="#6366f1", width=0.5)
                    ax.bar_label(bars, fmt="%d", padding=3, color="#0f172a", fontsize=9)
                    ax.set_title(f"Distribution of Category: {col} (Top 5)", fontsize=11, fontweight="bold", color="#0f172a")
                    ax.spines['top'].set_visible(False)
                    ax.spines['right'].set_visible(False)
                    ax.spines['left'].set_visible(False)
                    ax.yaxis.set_visible(False)
                    plt.xticks(fontsize=8)
                    plt.tight_layout()
                    buf = io.BytesIO()
                    plt.savefig(buf, format="png", dpi=150)
                    buf.seek(0)
                    buffers["categorical_dist"] = buf
                    plt.close(fig)
        except Exception:
            plt.close()

        return buffers

    @classmethod
    def build_report(
        cls, 
        df: pd.DataFrame, 
        df_summary: Dict[str, Any], 
        cleaning_logs: List[Any], 
        insights: List[Dict[str, Any]], 
        dataset_name: str, 
        version_number: int, 
        quality_score: float
    ) -> bytes:
        """Assembles a professional letter PDF report using Flowables."""
        
        pdf_buffer = io.BytesIO()
        doc = SimpleDocTemplate(
            pdf_buffer,
            pagesize=letter,
            rightMargin=54,
            leftMargin=54,
            topMargin=54,
            bottomMargin=54
        )

        styles = getSampleStyleSheet()
        
        # Define Custom Styles for a premium look
        title_style = ParagraphStyle(
            "ReportTitle",
            parent=styles["Title"],
            fontName="Helvetica-Bold",
            fontSize=26,
            leading=30,
            textColor=colors.HexColor("#0f172a"),
            alignment=0, # Left-aligned
            spaceAfter=15
        )

        subtitle_style = ParagraphStyle(
            "ReportSubtitle",
            parent=styles["Normal"],
            fontName="Helvetica",
            fontSize=12,
            leading=16,
            textColor=colors.HexColor("#475569"),
            spaceAfter=25
        )

        h1_style = ParagraphStyle(
            "SectionH1",
            parent=styles["Heading1"],
            fontName="Helvetica-Bold",
            fontSize=16,
            leading=20,
            textColor=colors.HexColor("#4f46e5"),
            spaceBefore=15,
            spaceAfter=10,
            keepWithNext=True
        )

        body_style = ParagraphStyle(
            "ReportBody",
            parent=styles["Normal"],
            fontName="Helvetica",
            fontSize=10,
            leading=14,
            textColor=colors.HexColor("#334155"),
            spaceAfter=8
        )

        bold_body = ParagraphStyle(
            "ReportBodyBold",
            parent=body_style,
            fontName="Helvetica-Bold"
        )

        table_header_style = ParagraphStyle(
            "TableHeader",
            parent=styles["Normal"],
            fontName="Helvetica-Bold",
            fontSize=9,
            leading=11,
            textColor=colors.white
        )

        table_body_style = ParagraphStyle(
            "TableBody",
            parent=styles["Normal"],
            fontName="Helvetica",
            fontSize=9,
            leading=11,
            textColor=colors.HexColor("#1e293b")
        )

        insight_title_style = ParagraphStyle(
            "InsightTitle",
            parent=styles["Normal"],
            fontName="Helvetica-Bold",
            fontSize=10,
            leading=13,
            textColor=colors.HexColor("#0f172a")
        )

        story = []

        # --- COVER / TITLE HEADER ---
        story.append(Paragraph("DataInsight AI", title_style))
        story.append(Paragraph(f"Comprehensive Analytics & Cleaning Report: <b>{dataset_name}</b>", subtitle_style))
        
        # Quality Score & Metadata Grid (Styled as Callouts)
        meta_data = [
            [
                Paragraph("<b>Active Version:</b>", body_style), Paragraph(f"v{version_number}", body_style),
                Paragraph("<b>Data Quality Score:</b>", body_style), Paragraph(f"<b>{quality_score}/100</b>", bold_body)
            ],
            [
                Paragraph("<b>Row Count:</b>", body_style), Paragraph(f"{df_summary['shape'][0]:,}", body_style),
                Paragraph("<b>Column Count:</b>", body_style), Paragraph(f"{df_summary['shape'][1]}", body_style)
            ],
            [
                Paragraph("<b>Memory Size:</b>", body_style), Paragraph(df_summary["memory_usage"], body_style),
                Paragraph("<b>Generated On:</b>", body_style), Paragraph(datetime.now().strftime("%Y-%m-%d %H:%M"), body_style)
            ]
        ]
        
        meta_table = Table(meta_data, colWidths=[1.5*inch, 1.8*inch, 1.7*inch, 2.0*inch])
        meta_table.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,-1), colors.HexColor("#f8fafc")),
            ('PADDING', (0,0), (-1,-1), 8),
            ('BOX', (0,0), (-1,-1), 1, colors.HexColor("#e2e8f0")),
            ('INNERGRID', (0,0), (-1,-1), 0.5, colors.HexColor("#f1f5f9")),
            ('ALIGN', (0,0), (-1,-1), 'LEFT'),
            ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
        ]))
        story.append(meta_table)
        story.append(Spacer(1, 20))

        # --- STATIC MATPLOTLIB CHARTS GENERATION ---
        charts = cls.generate_charts_as_buffers(df, df_summary)

        # --- SECTION 1: EXECUTIVE INSIGHTS ---
        story.append(Paragraph("1. AI Executive Insights", h1_style))
        story.append(Paragraph(
            "These insights describe business trends, data patterns, statistical correlations, and recommendations, automatically inferred from the dataset attributes.",
            body_style
        ))
        story.append(Spacer(1, 8))

        # List Insights
        for idx, insight in enumerate(insights):
            cat = (insight.get("category") or "trend").upper()
            title = insight.get("title") or f"Insight #{idx+1}"
            desc = insight.get("description") or ""
            importance = (insight.get("importance") or "medium").upper()
            
            # Category color tag
            cat_color = "#3b82f6" # Blue
            if cat == "ANOMALY":
                cat_color = "#ef4444" # Red
            elif cat == "CORRELATION":
                cat_color = "#ec4899" # Pink
            elif cat == "RECOMMENDATION":
                cat_color = "#f59e0b" # Orange
                
            insight_data = [
                [
                    Paragraph(f"<font color='{cat_color}'><b>[{cat}]</b></font> <b>{title}</b> (Importance: {importance})", insight_title_style)
                ],
                [
                    Paragraph(desc, body_style)
                ]
            ]
            insight_table = Table(insight_data, colWidths=[7.0*inch])
            insight_table.setStyle(TableStyle([
                ('BACKGROUND', (0,0), (-1,-1), colors.HexColor("#fdfdfd")),
                ('PADDING', (0,0), (-1,-1), 6),
                ('BOX', (0,0), (-1,-1), 0.5, colors.HexColor("#e2e8f0")),
                ('LINELEFT', (0,0), (0,-1), 3, colors.HexColor(cat_color)),
                ('TOPPADDING', (0,0), (-1,0), 6),
                ('BOTTOMPADDING', (0,-1), (-1,-1), 6),
            ]))
            story.append(insight_table)
            story.append(Spacer(1, 10))
            
        story.append(Spacer(1, 10))

        # --- SECTION 2: CLEANING LOGS / AUDIT TRAIL ---
        story.append(Paragraph("2. Data Cleaning & Transformation History", h1_style))
        story.append(Paragraph(
            "Below is the complete audit trail of the transformations applied to clean the dataset from its original raw version.",
            body_style
        ))
        story.append(Spacer(1, 8))

        if not cleaning_logs:
            story.append(Paragraph("<i>No data cleaning actions have been applied yet. Dataset is in its uploaded raw state.</i>", body_style))
        else:
            log_data = [[
                Paragraph("Action Type", table_header_style), 
                Paragraph("Target Column", table_header_style), 
                Paragraph("Details", table_header_style),
                Paragraph("Timestamp", table_header_style)
            ]]
            for log in cleaning_logs:
                # Support models.CleaningLog objects or schemas
                action_type = (log.action_type if hasattr(log, "action_type") else log.get("action_type")) or "Action"
                column_name = (log.column_name if hasattr(log, "column_name") else log.get("column_name")) or "Dataset"
                details = (log.details if hasattr(log, "details") else log.get("details")) or ""
                
                # Format Timestamp
                ts = log.timestamp if hasattr(log, "timestamp") else log.get("timestamp")
                if isinstance(ts, datetime):
                    ts_str = ts.strftime("%Y-%m-%d %H:%M")
                elif isinstance(ts, str):
                    ts_str = ts[:16].replace("T", " ")
                else:
                    ts_str = "N/A"

                log_data.append([
                    Paragraph(f"<b>{action_type}</b>", table_body_style),
                    Paragraph(column_name, table_body_style),
                    Paragraph(details, table_body_style),
                    Paragraph(ts_str, table_body_style)
                ])

            log_table = Table(log_data, colWidths=[1.5*inch, 1.4*inch, 2.7*inch, 1.4*inch])
            log_table.setStyle(TableStyle([
                ('BACKGROUND', (0,0), (-1,0), colors.HexColor("#4f46e5")),
                ('PADDING', (0,0), (-1,-1), 6),
                ('ALIGN', (0,0), (-1,-1), 'LEFT'),
                ('VALIGN', (0,0), (-1,-1), 'TOP'),
                ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor("#cbd5e1")),
                ('ROWBACKGROUNDS', (0,1), (-1,-1), [colors.white, colors.HexColor("#f8fafc")]),
            ]))
            story.append(log_table)
            
        # Draw Null values matplotlib chart in this page
        if "null_chart" in charts:
            story.append(Spacer(1, 15))
            story.append(KeepTogether([
                Paragraph("<b>Dataset Null Value Profile</b>", bold_body),
                Spacer(1, 5),
                Image(charts["null_chart"], width=5.5*inch, height=2.3*inch)
            ]))

        story.append(Spacer(1, 20))

        # --- SECTION 3: STATISTICAL EDA PROFILE ---
        story.append(Paragraph("3. Exploratory Data Analysis (EDA) Profile", h1_style))
        story.append(Paragraph(
            "Descriptive statistics for the active dataset columns, outlining data types, completion rates, central tendency, and dispersion indicators.",
            body_style
        ))
        story.append(Spacer(1, 8))

        stats_data = [[
            Paragraph("Column", table_header_style), 
            Paragraph("Type", table_header_style), 
            Paragraph("Count", table_header_style), 
            Paragraph("Mean", table_header_style),
            Paragraph("Median", table_header_style),
            Paragraph("Min", table_header_style),
            Paragraph("Max", table_header_style),
            Paragraph("Std Dev", table_header_style)
        ]]

        for col, stats in df_summary.get("descriptive_stats", {}).items():
            col_type = stats.get("type", "text")
            count = stats.get("count", 0)
            
            if col_type == "numeric":
                mean = f"{stats.get('mean'):.2f}" if stats.get("mean") is not None else "N/A"
                median = f"{stats.get('median'):.2f}" if stats.get("median") is not None else "N/A"
                min_v = f"{stats.get('min'):.2f}" if stats.get("min") is not None else "N/A"
                max_v = f"{stats.get('max'):.2f}" if stats.get("max") is not None else "N/A"
                std = f"{stats.get('std'):.2f}" if stats.get("std") is not None else "N/A"
            else:
                mean = "N/A"
                median = "N/A"
                min_v = "N/A"
                max_v = "N/A"
                std = "N/A"

            stats_data.append([
                Paragraph(f"<b>{col}</b>", table_body_style),
                Paragraph(col_type, table_body_style),
                Paragraph(f"{count:,}", table_body_style),
                Paragraph(mean, table_body_style),
                Paragraph(median, table_body_style),
                Paragraph(min_v, table_body_style),
                Paragraph(max_v, table_body_style),
                Paragraph(std, table_body_style)
            ])

        stats_table = Table(stats_data, colWidths=[1.3*inch, 0.8*inch, 0.7*inch, 0.9*inch, 0.9*inch, 0.8*inch, 0.8*inch, 0.8*inch])
        stats_table.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), colors.HexColor("#334155")),
            ('PADDING', (0,0), (-1,-1), 5),
            ('ALIGN', (0,0), (-1,-1), 'LEFT'),
            ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
            ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor("#cbd5e1")),
            ('ROWBACKGROUNDS', (0,1), (-1,-1), [colors.white, colors.HexColor("#f8fafc")]),
        ]))
        story.append(stats_table)

        # Heatmap Chart & Categorical Chart Side-by-Side or Stacked
        chart_flowables = []
        if "correlation_heatmap" in charts:
            chart_flowables.append(Image(charts["correlation_heatmap"], width=3.3*inch, height=3.0*inch))
        if "categorical_dist" in charts:
            chart_flowables.append(Image(charts["categorical_dist"], width=3.5*inch, height=1.75*inch))
            
        if chart_flowables:
            story.append(Spacer(1, 20))
            if len(chart_flowables) == 2:
                # Place side by side or stacked inside a borderless table
                chart_table_data = [[chart_flowables[0], chart_flowables[1]]]
                chart_table = Table(chart_table_data, colWidths=[3.5*inch, 3.5*inch])
                chart_table.setStyle(TableStyle([
                    ('VALIGN', (0,0), (-1,-1), 'TOP'),
                    ('ALIGN', (0,0), (-1,-1), 'CENTER'),
                    ('LEFTPADDING', (0,0), (-1,-1), 0),
                    ('RIGHTPADDING', (0,0), (-1,-1), 0),
                ]))
                story.append(KeepTogether([
                    Paragraph("<b>Visual Profile Charts</b>", bold_body),
                    Spacer(1, 5),
                    chart_table
                ]))
            else:
                story.append(KeepTogether([
                    Paragraph("<b>Correlation Map</b>", bold_body),
                    Spacer(1, 5),
                    chart_flowables[0]
                ]))

        # Build PDF
        doc.build(story, canvasmaker=NumberedCanvas)
        pdf_buffer.seek(0)
        return pdf_buffer.getvalue()
